### ISSUE TITLE
Open Graph for Homepage

### ISSUE THREAD

**Issue by WarenGonzaga** [wareneutron/psgc-api#13]
We need to add default open graph for the homepage so when we share the URL it will preview correctly on social media sites.

**Comment by davebanguilan** [comment]
Hi sir, @WarenGonzaga. You can assign it to me.

**Comment by WarenGonzaga** [comment]
Thanks @davebanguilan I'll send the assets here and additional instructions.

**Comment by WarenGonzaga** [comment]
Hi @davebanguilan here's the assets you need for the open graph.

[opengraph-assets.zip](https://github.com/wareneutron/psgc-api/files/6207740/opengraph-assets.zip)

Instructions:

1. Generate favicons based on the logo inside the assets package. You can use this [link](https://favicon.io/favicon-converter/) for creating favicons.
2. After generating the favicons copy the meta tags from that generator.
3. Add your changes to the ``index.html``
4. Create ``assets`` folder and place the favicon inside that folder.
5. Place the open graph banner inside the ``asset`` folder and use it.

After that, push your changes and create PR. Ask me for review or mention me.
Feel free to reach out to me if you have any questions regarding your contribution.

Have a great day!

**Comment by WarenGonzaga** [comment]
Will close this as it is now solved. @davebanguilan you just earned a contributor badge on our Discord server.
