### ISSUE TITLE
Front-End for API is Unresponsive on Mobile view

### ISSUE THREAD

**Issue by WarenGonzaga** [wareneutron/psgc-api#14]
The front-end of the API has issues on mobile view.

**Comment by WarenGonzaga** [comment]
Preview of said issue...

![image](https://user-images.githubusercontent.com/15052701/111991132-eb84f000-8b4e-11eb-9021-bdadd451146e.png)

**Comment by jcads** [comment]
Can I work on this one?

**Comment by WarenGonzaga** [comment]
> Are you accepting other contributors? If so, can I work on this one?

Yes sure! Just submit a PR on dev branch and we'll review it.

**Comment by WarenGonzaga** [comment]
Fixed in #16 thanks @jcads
